name: 'Prepare Automated Release'
description: 'Prepares a release by back merging main into develop and creating an automated release branch if marked for semver release.'

inputs:
  back_merge_branch:
    description: 'Branch to back merge into.'
    required: false
    default: ${{ github.event.repository.default_branch }}
