name: Test gha-prep-release

on:
  push:
    branches:
      - main
      - develop

jobs:
  test-gha-prep-release:
    runs-on: ubuntu-latest
    name: Test gha-prep-release
    steps:
      - name: Run gha-prep-release
        uses: alehechka/gha-prep-release@develop
        with:
          skip_back_merge: true

      - name: Run gha-prep-release (semver_tag)
        uses: alehechka/gha-prep-release@develop
        with:
          skip_back_merge: true
          semver_tag: 'hardcode-semver'
