name: Test gha-prep-release

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  test-gha-prep-release:
    runs-on: ubuntu-latest
    name: Test gha-prep-release
    steps:
      - name: Run gha-prep-release (non-main)
        if: github.ref_name != 'main'
        id: commit-tag
        uses: dmsi-io/gha-prep-release@develop
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          skip_back_merge: true
          skip_create_branch: true

      - name: Run gha-prep-release (semver_tag)
        id: provided-tag
        uses: dmsi-io/gha-prep-release@develop
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          skip_back_merge: true
          semver_tag: 'hardcode-semver'

      - name: Print Tags
        run: |
          echo "Commit Tag: ${{ steps.commit-tag.outputs.tag }}"
          echo "Provided Tag: ${{ steps.provided-tag.outputs.tag }}"
