name: Test gha-prep-release

on:
  push:
    branches:
      - main
      - develop

jobs:
  test-gha-prep-release:
    runs-on: ubuntu-latest
    name: Test gha-prep-release
    steps:
      - name: Run gha-prep-release
        id: commit-tag
        uses: alehechka/gha-prep-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run gha-prep-release (semver_tag)
        id: provided-tag
        uses: alehechka/gha-prep-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          skip_back_merge: true
          semver_tag: 'hardcode-semver'

      - name: Print Tags
        run: |
          echo "Commit Tag: ${{ steps.commit-tag.outputs.tag }}"
          echo "Provided Tag: ${{ steps.provided-tag.outputs.tag }}"
