name: Release gha-prep-release

on:
  push:
    branches:
      - main

jobs:
  test-gha-prep-release:
    runs-on: ubuntu-latest
    name: Test gha-prep-release
    steps:
      - name: Prep Release
        id: main-commit-tag
        uses: dmsi-io/gha-prep-release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          skip_create_branch: true

      - name: Print Tags
        run: |
          echo "Commit Tag: ${{ steps.main-commit-tag.outputs.tag }}"

      - uses: actions-ecosystem/action-push-tag@v1
        if: steps.main-commit-tag.outputs.tag != ''
        with:
          tag: ${{ steps.main-commit-tag.outputs.tag }}
          message: '${{ steps.main-commit-tag.outputs.tag }}: Prepare Release Branch'
